[package]
name = "boobies"
version = "0.1.0"
authors = ["Bèr Kessels <ber@berk.es>"]
edition = "2021"

description = "Art experiments: Rounded Mazes"
keywords = ["creative", "sketch", "graphics", "art"]
license = "MIT"

[dependencies]
nannou = "0.19"
bertools = { path = "../bertools" }
